# invit config file (yaml)
patch_size: 8 # 32 Input image size: 128x128 -> 4x4 patches, 
hidden_size: 256
num_hidden_layers: 4
num_attention_heads: 4
intermediate_size: 1024 # 4 * hidden_size
hidden_dropout_prob: 0.1
attention_probs_dropout_prob: 0.1 
initializer_range: 0.02 
image_size: 64 # 一旦クロップ後のサイズ
crop_size: 64
num_classes: 10 # num_classes of CIFAR10
num_channels: 3
qkv_bias: true
use_faster_attention: true
batch_size: 128 # max 128x128x128
epochs: 50
lr: 1e-5
save_model_every: 0